#!/system/bin/sh 

# .::The Great::Dash-M::.
# by myaservip
####Thanks To :
#Chainfire
#JynAlek
#Rhievaldo
#Pikachu01
#Lenarox's
#TWR Team- SpaceCaker-SniperKiller-Rhedification-Vishnu PV
#Juwe11
#Imbawind 
#slaid480
#darky
#Every Dash User
#zeppelinrox
################################################

##SYSTEM ZIPALLIGNER
 
#Interval between ZipAlign runs, in seconds, 86400=24 hours
RUN_EVERY=86400

LOG_FILE=/data/mvip/zipalign.log
ZIPALIGNDB=/data/zipalign.db

if [ -e $LOG_FILE ]; then
  rm $LOG_FILE;
fi;

if [ ! -f $ZIPALIGNDB ]; then
  touch $ZIPALIGNDB;
fi;


echo "Starting FV Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE

for DIR in /system/app /data/app ; do
  cd $DIR
  for APK in *.apk ; do
    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ] ; then
      echo "Already checked: $DIR/$APK" | tee -a $LOG_FILE
    else
      zipalign -c 4 $APK
      if [ $? -eq 0 ] ; then
        echo "Already aligned: $DIR/$APK" | tee -a $LOG_FILE
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      else
        echo "Now aligning: $DIR/$APK" | tee -a $LOG_FILE
        zipalign -f 4 $APK /cache/$APK
        busybox mount -o rw,remount /system
        cp -f -p /cache/$APK $APK
        busybox rm -f /cache/$APK
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      fi
    fi
  done
done

busybox mount -o ro,remount /system
touch $ZIPALIGNDB
echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE